version: '3.1'

services:

  wordpress:
    depends_on:
       - db
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: 192.168.8.101
      WORDPRESS_DB_USER: 
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - themes:/usr/src/wordpress

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

  adminer:
    depends_on:
       - db
    image: adminer
    restart: always
    ports:
      - 7070:8080
    volumes:
      - ./zeszyty.sql:/var/www/html/adminer.sql

volumes:
  wordpress:
  db:
