version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./containers/mysql/my.cnf:/etc/mysql/my.cnf
       - ./import.sql:/tmp/import.sql
     #restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: webdevops/php-apache:7.4
     volumes:
       - ./wordpress:/app
       - ./containers/apache_php/php.ini:/opt/docker/etc/php/php.ini
     ports:
       - "8000:80"
     #restart: always
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

  adminer:
    depends_on:
       - db
    image: adminer
    #restart: always
    ports:
      - 7070:8080

volumes:
    db_data: {}
