## my global config
#global:
#  scrape_interval:     15s # By default, scrape targets every 15 seconds.
#  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
#  # scrape_timeout is set to the global default (10s).
#
#  # Attach these labels to any time series or alerts when communicating with
#  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#    monitor: 'scraping_workshop'
#
## Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - 'alert.rules'
#  # - "first.rules"
#  # - "second.rules"
#
## alert
#alerting:
#  alertmanagers:
#    - scheme: http
##    - static_configs:
##        - targets:
##            - "alertmanager:9091"
#
## A scrape configuration containing exactly one endpoint to scrape:
## Here it's Prometheus itself.
#scrape_configs:
#  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#
#  - job_name: 'prometheus'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
##    static_configs:
##      - targets: ['localhost:9090']
#
#
#  - job_name: 'cadvisor'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
##    static_configs:
##      - targets: ['cadvisor:8081']
#
#  - job_name: 'node-exporter'
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
##    static_configs:
##      - targets: ['node-exporter:9100']
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'nodeexporter:9100'

  - job_name: 'postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'postgres_exporter:9187'

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cadvisor:8081'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets:
        - 'pushgateway:9091'


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
